$("#modal_area").html("<%= escape_javascript(render(partial: 'billing_report')) %>")
$("#modal_place").modal('show')
$('#start_date').datetimepicker(format: 'MM-DD-YYYY')
$('#end_date').datetimepicker(format: 'MM-DD-YYYY')
$("#protocol_ids").selectpicker()
