$("#modal_area").html("<%= escape_javascript(render(partial: @report_type, locals: { title: @title })) %>")
$("#modal_place").modal('show')
$('#start_date').datetimepicker(format: 'MM-DD-YYYY')
$('#end_date').datetimepicker(format: 'MM-DD-YYYY')
$("#protocol_id").selectpicker()